### ISSUE TITLE
Implement subcycling in YOG as an option

### ISSUE THREAD

**Issue by jatkinson1000** [m2lines/CAM-ML#17]
As has been discussed previously in the project, there may be a need to implement subcycling in the YOG parameterisation as it was trained on a much shorter timestep in SAM than is used in CAM.

No that we can run online with a single CAM timestep (#14) we can look at implementing this.

@paogorman comments:

The precip looked pretty good but we saw that relative humidity was getting low in the upper troposphere sometimes, so we need to look into that.
One possibility would be testing if subcyling the timestep matters.
Or it could be that both clubb and YOG are active in this region leading to overly strong tendencies.

To implement this I would propose fixing the sub-timestep at the SAM timestep, and calling the parameterisation multiple times in a loop as many times as are required to complete the full CAM timestep.
Care would need to be taken to accumulate the relevant variables and tendencies correctly.

**Comment by jatkinson1000** [comment]
Alternative suggestion from @paogorman:

CAM already subcycles with CLUBB, and CAM interacts closely with CLUBB

Suggestion is to move YOG to the CLUBB subcycling loop and alternating YOG and CLUBB.

A further comment is that subcycling will kill efficiency, so we should not follow this path as a development rather as a test to see if it makes a difference that may or may not be required.

**Comment by MarionBWeinzierl** [comment]
@paogorman investigated this and feels it is not necessary. Note that this was done by running the scheme alongside CLUBB to make use of the subcycling already in place there.
