### ISSUE TITLE
remove unnecessary SAM-specific code from NN-interface_cam.F90

### ISSUE THREAD

**Issue by paogorman** [m2lines/CAM-ML#25]
Remove nstep, nstatis, icycle, precsfc_i. These make sense in SAM but not CAM.

Remove duplicate setting of tabs0_sam=tabs_sam:
https://github.com/m2lines/CAM-ML/blob/facd0cee74a7c4017501d49e9d51221fc875df8b/src/physics/cam/nn_interface_cam.F90#L189-L193

**Comment by jatkinson1000** [comment]
This is addressed in #29 for review alongside other review updates.
