### ISSUE TITLE
new min function in nn_convection_flux.f90?

### ISSUE THREAD

**Issue by paogorman** [m2lines/CAM-ML#26]
I don't see the min function on this line in Janni's original repository:

https://github.com/m2lines/CAM-ML/blob/facd0cee74a7c4017501d49e9d51221fc875df8b/src/physics/cam/nn_convection_flux.F90#L360

It prevents a negative contribution to precipitation from sedimentation. One could debate whether we should have that constraint, but in any event I think we were trying to stick to Janni's approach where possible. Did I miss it somewhere?

**Comment by jatkinson1000** [comment]
We had a discussion in a previous meeting about whether to enforce a constraint to prevent negative sedimentation at the surface.

This included:
- Could negative sedimentation in some way represent evaporation?
- Should we apply a constraint if the net has 'learnt' negative sedimentation at the surface?
  - Where would it have 'learnt' it from, and does SAM enforce non-negative at the surface?

I can change it back to match Janni's approach if that is now preferable.

**Comment by jatkinson1000** [comment]
I have reverted this in #29 along with some other points you raised for review.
