### ISSUE TITLE
whether to use midpoint in pressure or z of cell when interpolating/converting variables

### ISSUE THREAD

**Issue by paogorman** [m2lines/CAM-ML#28]
We currently seem to use the midpoint in pressure when interpolating and converting variables:
https://github.com/m2lines/CAM-ML/blob/facd0cee74a7c4017501d49e9d51221fc875df8b/src/physics/cam/nn_interface_cam.F90#L540-L543

But elsewhere we say we are using midpoint in z:
https://github.com/m2lines/CAM-ML/blob/facd0cee74a7c4017501d49e9d51221fc875df8b/src/physics/cam/nn_interface_cam.F90#L291-L292

It would be good to make the comment consistent with the code. Also I was wondering what are the pros and cons of this choice?

**Comment by jatkinson1000** [comment]
Thanks, good spot - I will make a branch to fix a number of these changes and tag you for a review.

I made the decision to use pressure centres as the conservative interpolation scheme asks for a midpoint in pressure and the CAM grid we are working on is defined in pressure. I felt it made sense to define a centre pressure for the SAM cells rather than try anything more complex.

It was a tricky bug to catch as to why the tests I wrote for the conservative scheme were failing until I twigged that the pressure at an altitude midpoint was not the same as the midpoint pressure.

We can discuss pros/cons in the meeting?

**Comment by paogorman** [comment]
I understand the motivation from the point of view of the conservative regridding. But does this also mean that the original variables defined at cell centers are now at slightly the wrong pressure?

**Comment by jatkinson1000** [comment]
I remember thinking about this at the time for conservative interpolation.
The way I reasoned it was that for conservative interpolation the centre of the cell is not used - only the position of the interfaces.
We assume that the variable value defined at the cell centre is the same and distributed across the entire cell for the purpose of multiplying by $\Delta V$.
So the value at the cell geometric centre is the same as at the pressure centre (and the same everywhere in the cell) for the conservative interpolation.

For the linear interpolation of inputs I agree that the CAM input variables would now be interpolated to the pressure centres of the SAM cells, and the NN was trained on values at the geometric centres (and unlike the conservative regridding we should no longer treat the variable as constant across the cell volume).

This could be resolved, I think, by interpolating to the pressure at the geometric centre of the SAM cells for the inputs.
As defined in the `pres` variable here:
https://github.com/m2lines/CAM-ML/blob/facd0cee74a7c4017501d49e9d51221fc875df8b/src/physics/cam/nn_interface_cam.F90#L519-L521
But leaving the conservative regridding as it currently is based on `pres_mid`.

Does that sound sensible?

**Comment by paogorman** [comment]
Hi Jack,
I think I'm confused about the original problem that lead to switching to midpoint pressures. 
You said earlier: "I made the decision to use pressure centres as the conservative interpolation scheme asks for a midpoint in pressure and the CAM grid we are working on is defined in pressure. "
But I think you said later that the conservative interpolation just needs the pressures at the interfaces and assumed variables are constant in between. So why does the conserviatve scheme need the midpoint if it just uses the interaces?

**Comment by jatkinson1000** [comment]
Just checked the code, and the pressure-midpoint pressure array is 'created' during the conservative interpolation scheme, but it seems it never gets used - my guess is that it was used in a previous implementation of the scheme (when I worked through the thought process above) and has been accidentally left in.

With this I agree that we can definitely revert to using 'pressure at the geometric centre' of SAM cells. I will create a new branch to implement this and let you know when it is ready for a review.

**Comment by jatkinson1000** [comment]
I believe I have implemented this change in #31 which I have added you to as a reviewer.
