### ISSUE TITLE
Investigate timing changes using YOG vs ZM

### ISSUE THREAD

**Issue by jatkinson1000** [m2lines/CAM-ML#33]
CAM output timing files.
Work out what we need to sum/difference to get a meaningful comparison.

**Comment by jatkinson1000** [comment]
Exploting this with @MarionBWeinzierl there is timing information placed in `$CASEROOT` under `timing/`.

The single column cases are really to small to say anything conclusive, so an aquaplanet comparison would be preferable here.

We will also need to extend the level logging operates to to capture the timing that has been implemented for timing `yog_nn` in `physpkg.F90`.

**Comment by MarionBWeinzierl** [comment]
Timing code should be in `perf_mod`

**Comment by jatkinson1000** [comment]
`perf_mod` and timing systems is not part of CAM, but instead part of CIME.
It can be found at `cime/src/share/timing/`.

CIME timing documentation can be found here: https://esmci.github.io/cime/versions/maint-5.6/html/users_guide/timers.html?highlight=timing

**Comment by MarionBWeinzierl** [comment]
To be more precise, on Derecho the timing output can be found under `/glade/u/<username>/<case>/run/timing` as well as in cases directory under `timing`. Timing should be on by default, but can be explicitly set by `./xmlchange CHECK_TIMING=TRUE`

**Comment by MarionBWeinzierl** [comment]
Overall runtimes for single column Toga II run:
![togaII_YOG](https://github.com/user-attachments/assets/a8a26638-f2ad-4447-b938-0cafdcec0ccd)

The same with ZM:
![togaII_ZM](https://github.com/user-attachments/assets/4443f078-c458-444d-96cc-eb2876c24351)

**Comment by MarionBWeinzierl** [comment]
Another run of both, this time at the same time: 

YOG:
![image](https://github.com/user-attachments/assets/2167eeef-e243-4bbe-aaf1-7f3f93feb1d1)


ZM: 
![image](https://github.com/user-attachments/assets/5ee760b3-f9db-4fc5-82bc-d271832199e2)

**Comment by MarionBWeinzierl** [comment]
The aqua planet runs for ZM and YOG :point_down:. Again, YOG seems slightly faster. But This was just a 5 day run, so I need to do the 100 days run you suggested. Just want to make sure I am running the right thing. The command I used for building the case was `../cesm/cime/scripts/create_newcase --case aqua_sst_ZM --srcroot /glade/u/home/weinzierl/cesm/ --compset QPC6 --res f19_f19_mg17 --user-mods-dir ~/cesm/components/cam/cime_config/usermods_dirs/aquap --project NCGD0054 ` . Does that look about right?

![image](https://github.com/user-attachments/assets/6db0acd0-e4fb-4585-8afe-4827e43d1666)
![image](https://github.com/user-attachments/assets/0c6b78a9-0e68-46cc-81a1-9e978c972b2d)

Also, I mentioned in our last meeting that the aquaplanet was crashing for me. That was for NTASKS=256 , which works fine for ZM, but crashes for YOG with something like

> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: forrtl: severe (174): SIGSEGV, segmentation fault occurred
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: Image              PC                Routine            Line        Source
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: libpthread-2.31.s  000014745B8758C0  Unknown               Unknown  Unknown
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           0000000000ED7BD4  rrtmg_sw_taumol_m         274  rrtmg_sw_taumol.f90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           0000000000ED0241  rrtmg_sw_spcvmc_m         300  rrtmg_sw_spcvmc.f90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           0000000000EC765E  rrtmg_sw_rad_mp_r         497  rrtmg_sw_rad.f90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           000000000075A392  radsw_mp_rad_rrtm         515  radsw.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           000000000073B3D1  radiation_mp_radi        1105  radiation.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           00000000006F2FF5  physpkg_mp_tphysb        2301  physpkg.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           00000000006EBEB8  physpkg_mp_phys_r        1065  physpkg.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           0000000000501DC6  cam_comp_mp_cam_r         258  cam_comp.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           00000000004F70E0  atm_comp_mct_mp_a         287  atm_comp_mct.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           0000000000438E98  component_mod_mp_         267  component_mod.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           000000000042D573  cime_comp_mod_mp_        2015  cime_comp_mod.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           000000000043600B  MAIN__                    114  cime_driver.F90
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           00000000004196FD  Unknown               Unknown  Unknown
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: libc-2.31.so       000014745793229D  __libc_start_main     Unknown  Unknown
> [dec2466.hsn.de.hpc.ucar.edu](http://dec2466.hsn.de.hpc.ucar.edu/) 219: cesm.exe           000000000041962A  Unknown               Unknown  Unknown

The above screenshots are for NTASKS=64

**Comment by MarionBWeinzierl** [comment]
I did 100 day runs of the aquaplanet with `--compset QPC6 --res f09_f09_mg17` . this one sets NTASKS automatically to NTASKS: `['CPL:512', 'ATM:512', 'LND:512', 'ICE:512', 'OCN:512', 'ROF:512', 'GLC:512', 'WAV:512', 'ESP:1']`  (as opposed to giving just a single number, as for the `f19_f19_mg17` ones I ran before. No problem with running it for YOG.

Again, the performance of YOG and ZM is very similar, with YOG slightly but not significantly faster.

**Comment by MarionBWeinzierl** [comment]
YOG:

![Image](https://github.com/user-attachments/assets/0a675088-a08f-4d47-8348-86511e24be7f)

ZM:
![Image](https://github.com/user-attachments/assets/05cac50e-6667-46bb-b395-2f1c7982c5ad)

**Comment by MarionBWeinzierl** [comment]
Rerunning the aquaplanet with `CAM-ML` (instead of `CAM-ML-tmp`) branch, and reducing the output as suggested by @paogorman .

YOG:
![Image](https://github.com/user-attachments/assets/e7d7dc8a-83ec-4aad-b18d-aced9e35595f)

ZM:
![Image](https://github.com/user-attachments/assets/16c47cfb-dcb6-430f-bdc1-6bdb5a3bc0b5)

Here, ZM is slightly faster.

**Comment by MarionBWeinzierl** [comment]
Overall, we are happy enough to see that the YOG scheme is not significantly slower than ZM.

We will have another look at the timing files when all changes have been implemented.
