### ISSUE TITLE
Examine banding in Aquaplanet simulations

### ISSUE THREAD

**Issue by jatkinson1000** [m2lines/CAM-ML#47]
This issue is to track the apparent horizontal banding observed in some variables in aquaplanet simulations using the YOG scheme.

This has been noted by @jatkinson1000 in some cloud variables, and by @paogorman in "`YOGDQ` at 912hpa in the h1 file"

It was initially suspected that this could be due to domain decomposition, but this was investigated in #41 and it seems that it is not responsible (see discussion and conformation from Jesse NCAR).
#40 has been closed, so I am opening this to track this more generally.

**Comment by paogorman** [comment]
Based on the output of yogdq, I think it looks like the latitude and longitude locations are getting messed up somehow. For example, there seems to be no connection between spatial patterns in specific humidity and the output yogdq.
Here is an example of the kind of bug I would suggest looking for: Currently yog_intr.f90 passes ptend%q compnents as an argument to nn_convection_flux.f90. These arrays have size pcols in the first dimension. But nn_convection_flux.f90 defines these output arrays as having size ncol which need not be the same size as pcols. This may not be the origin of the problem, but I would look for an issue of this type.
